# Generated by Django 4.1.7 on 2023-04-04 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100)),
                ('doc_spec', models.TextField(max_length=200)),
                ('doc_image', models.ImageField(upload_to='doctor')),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.department')),
            ],
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
